apiVersion: v1
kind: Service
metadata:
  name: guessing-game-svc
  namespace: lab-demo-ext
spec:
  selector:
    app: guessing-game
    label: Green
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 32767
  type: NodePort
